### ISSUE TITLE
Problems with examples

### ISSUE THREAD

**Issue by elinw** [UrbanInstitute/education-data-package-r#55]
I tried running 
```
get_education_data(level = 'school-districts', source = 'ccd', topic = 'finance')
```
from the help page and also
```
df <- get_education_data(level = 'schools', 
                         source = 'ccd', 
                         topic = 'enrollment', 
                         by = list('race', 'sex'),
                         filters = list(year = 2008,
                                        grade = 9:12,
                                        ncessch = '340606000122'),
                         add_labels = TRUE)
```
And both failed with this message (obviously the first line differed).

> Fetching data for school-districts/ccd/finance/1991/ ...
> Error: Query page not found.
> Please double-check your arguments (especially filters).
> Consider filing an issue with the development team if this issue persists.
> 

Commenting out the filters for the second one solved the issue from what I can tell (I didn't let it run to completion).

I believe based on the endpoint data that the problem is the filter for grades:
`grade = 9:12`  does not work, it needs to be e.g  `grade= "grade-9"`

**Comment by khueyama** [comment]
Thanks for the feedback @elinw! It appears that the `school-districts/ccd/finance` endpoint is currently down. I've filed the issue with our development team and will let you know when it's back online. 

I was able to run the second example just now, the package is setup so that you can specify grade as just the integer value you want instead of having to specify `grade-9`, etc. In your case I'm assuming the endpoint timed out for some reason. I'll add a feature in the next release which will make that clearer than the error message you received.

**Comment by khueyama** [comment]
@elinw The `school-districts/ccd/finance` endpoint is back online.

For your second issue, I've updated the R package to provide a clearer error message when the API returns a timeout issue. 

Thanks again for using the package and for the helpful feedback! Let me know if you have any other questions or issues.
